In [1]:
import tensorflow as tf

In [3]:
vocab = ["a", "b", "c", "d"]
data = tf.constant([["a", "c", "d"], ["d", "z", "b"]])
layer = tf.keras.layers.StringLookup(vocabulary=vocab)
layer(data)



<tf.Tensor: shape=(2, 3), dtype=int64, numpy=
array([[1, 3, 4],
       [4, 0, 2]], dtype=int64)>

In [5]:
layer = tf.keras.layers.StringLookup()
layer.adapt(data)
layer.get_vocabulary()

# OOV token "[UNK]"가 어휘에 추가되었으며 나머지 토큰은 빈도에 따라 정렬된 뒤 역 정렬로 정렬된다.

['[UNK]', 'd', 'z', 'c', 'b', 'a']

## one-hot

In [6]:
vocab = ["a", "b", "c", "d"]
data = tf.constant(["a", "b", "c", "d", "z"])
layer = tf.keras.layers.StringLookup(
    vocabulary=vocab, output_mode='one_hot')
layer(data)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0.]], dtype=float32)>

https://www.tensorflow.org/api_docs/python/tf/keras/layers/StringLookup